title: Marha Midhatiey
description: AI Engineer | Applied AI Research | LLMs & Deep Learning
url: https://mareuu.github.io
baseurl: ""

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: Marha Midhatiey
  avatar: /assets/images/IMG-4325-removebg-preview.png
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/Mareuu
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/marhamidhatiey

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
